# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SLG' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart Lifeguard
  pod 'AWSCognito'
  pod 'AWSCore'
  pod 'AWSIoT'
  pod 'AWSMobileClient'

  target 'SLGTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SLGUITests' do
    # Pods for testing
  end

end
